#:schema node_modules/wrangler/config-schema.json
name = "hammer"
main = "dist/index.js"
workers_dev = false
upload_source_maps = true
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[build]
command = "pnpm run build"
watch_dir = "src"

[env.production]
route = 'hammer.atora.workers.dev'
